export type AlbumTheme = 'editorial' | 'masonry' | 'polaroid' | 'filmstrip' | 'grid' | 'vintage';

export type PhotoCategory = 'people' | 'places' | 'things' | 'styles';

export interface ScriptureVerse {
  reference: string;
  text: string;
  theme: string;
}

export interface FaceDetection {
  id: string;
  name: string;
  avatarUrl?: string;
  confidence: number;
  box?: {
    x: number; // percentage (0-100)
    y: number;
    w: number;
    h: number;
  };
}

export interface PhotoMetadata {
  camera?: string;
  lens?: string;
  focalLength?: string;
  aperture?: string;
  iso?: number;
  shutterSpeed?: string;
  resolution?: string;
  fileSize?: string;
}

export interface PhotoLocation {
  name: string;
  city?: string;
  country?: string;
  lat?: number;
  lng?: number;
}

export interface Photo {
  id: string;
  url: string;
  thumbnailUrl: string;
  title: string;
  description?: string;
  story?: string; // Full descriptive story & journal notes
  date: string; // YYYY-MM-DD
  time?: string;
  timestamp: number;
  location: PhotoLocation;
  albumIds: string[];
  tags: string[];
  faces: FaceDetection[];
  metadata: PhotoMetadata;
  isFavorite: boolean;
  isBackedUp: boolean;
  googlePhotoId?: string;
  source: 'google_photos' | 'local_upload' | 'synced';
  // Categorization according to people, places, things, styles
  category?: PhotoCategory;
  placeCategory?: string;
  thingCategory?: string;
  styleCategory?: string;
  // Spiritual & Bible Verse pairing
  spiritualVerse?: ScriptureVerse;
  spiritualTheme?: string;
}

export interface Collaborator {
  id: string;
  name: string;
  email: string;
  avatar: string;
  role: 'owner' | 'editor' | 'viewer';
}

export interface AlbumComment {
  id: string;
  author: string;
  avatar: string;
  text: string;
  timestamp: number;
}

export interface Album {
  id: string;
  title: string;
  description: string;
  theme: AlbumTheme;
  coverPhotoUrl: string;
  startDate: string;
  endDate: string;
  tags: string[];
  customAccentColor: string;
  isShared: boolean;
  shareLink: string;
  collaborators: Collaborator[];
  comments: AlbumComment[];
  googlePhotosAlbumId?: string;
  isAutoGenerated?: boolean;
}

export interface PersonCluster {
  id: string;
  name: string;
  avatarUrl: string;
  photoCount: number;
  relation: string;
}

export type BookCoverType = 'hardcover' | 'linen' | 'softcover' | 'leatherette';
export type BookPaperType = 'lustre' | 'matte' | 'glossy';
export type BookPageLayout = 'single-bleed' | 'two-photo' | 'collage-3' | 'quote-photo';

export interface BookPage {
  pageNumber: number;
  layout: BookPageLayout;
  photoIds: string[];
  caption?: string;
  quote?: string;
}

export interface PhotoBook {
  id: string;
  albumId: string;
  title: string;
  subtitle: string;
  coverType: BookCoverType;
  paperType: BookPaperType;
  size: '8x8' | '10x10' | '12x12' | '8.5x11';
  pages: BookPage[];
  price: number;
  status: 'draft' | 'ordered' | 'printed';
}

export interface SyncStatus {
  isSyncing: boolean;
  lastSyncedAt: number | null;
  autoSyncEnabled: boolean;
  itemsSynced: number;
  cloudStorageUsedBytes: number; // e.g. 42.8 GB
  cloudStorageTotalBytes: number; // e.g. 100 GB
  backupVerified: boolean;
}
